### ISSUE TITLE
Redis Cluster support

### ISSUE THREAD

**Issue by nantiferov** [fetlife/redis-analyzer#5]
Hi,

Thank you for this wonderful tool. I was using mentioned in readme redis analysers in ruby and python and this one is way better and much more useful when you need to debug what stored in redis and how much memory keys take.

I tested this tool today against one of the nodes in Redis Cluster and apparently cluster isn't supported. Log:

```log
$ redis-analyzer -u replica_host:6378/0
thread 'main' panicked at src/analyzer.rs:147:18:
memory usage command: An error was signalled by the server: 4617 master_host:6379
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
So basically I run analyzer against **replica_host**, but it probably got redirect and went to **master_host** and then failed.
I can provide backtrace, but I think it should be reproducible on any Redis Cluster.

Versions:
* redis 7.0.8
* redis-analyzer 0.3.0

I think easiest solution for this would be to ignore internal redirects and analyze what is located on each node without trying to collect full picture from whole cluster, since it could be time consuming and create too much load.

**UPD:** v0.3.0 works with master nodes (showing stats for single node keys only), but fails for replicas. v0.4.0 fails on both master and replicas.

**Comment by gtzinos** [comment]
You can try the following pull request https://github.com/fetlife/redis-analyzer/pull/6

**Comment by nantiferov** [comment]
Tested current **master** branch (**v0.4.0**), which should have changes from that PR (as it closed), behavior slightly changed, but still fails:

```log
$ redis-analyzer -u 127.0.0.1:6379/0
failed to get key: failed to get key
failed to get key: failed to get key
failed to get key: failed to get key
failed to get key: failed to get key
failed to get key: failed to get key
failed to get key: failed to get key
failed to get key: failed to get key
failed to get key: failed to get key
failed to get key: failed to get key
failed to get key: failed to get key
failed to get key: failed to get key
failed to get key: failed to get key
failed to get key: failed to get key
failed to get key: failed to get key
failed to get key: failed to get key
failed to get key: failed to get key
failed to get key: failed to get key

thread 'main' (402656) panicked at src/analyzer.rs:148:62:
scan: Cannot convert from UTF-8- TypeError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by nantiferov** [comment]
Build from that [PR](https://github.com/fetlife/redis-analyzer/pull/6) fails as well:

```log
$ redis-analyzer -u 127.0.0.1:6379/0
thread 'main' (403115) panicked at src/analyzer.rs:74:34:
Failed to get key from Redis: Incompatible type - Cannot convert from UTF-8: invalid utf-8 sequence of 1 bytes from index 42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by nantiferov** [comment]
Just in case tested yours [PR](https://github.com/fetlife/redis-analyzer/pull/8), same issue:

```log
$ redis-analyzer -u 127.0.0.1:6379/0
Error retrieving key: failed to get key
Error retrieving key: failed to get key
Error retrieving key: failed to get key
Error retrieving key: failed to get key
Error retrieving key: failed to get key
Error retrieving key: failed to get key
Error retrieving key: failed to get key
Error retrieving key: failed to get key
Error retrieving key: failed to get key
Error retrieving key: failed to get key
Error retrieving key: failed to get key
Error retrieving key: failed to get key
Error retrieving key: failed to get key
Error retrieving key: failed to get key
Error retrieving key: failed to get key
Error retrieving key: failed to get key
Error retrieving key: failed to get key

thread 'main' (403531) panicked at src/analyzer.rs:152:62:
scan: Cannot convert from UTF-8- TypeError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
